version: '3'

services:
  machine_1:
    container_name: machine_1
    image: alpine:3.15.5
    restart: always
    stdin_open: true
    tty: true
    networks:
      static-network:
        ipv4_address: 192.168.10.1
        aliases:
          - machine_1

  machine_2:
    container_name: machine_2
    image: alpine:3.15.5
    restart: always
    stdin_open: true
    tty: true
    networks:
      static-network:
        ipv4_address: 192.168.10.2
        aliases:
          - machine_2

networks:
  static-network:
    ipam:
      config:
        - subnet: 192.168.10.0/16
